# action.yml
name: 'OneTest Action'
description: ''
inputs:
  ask-config:  # id of input
    description: 'ask config'
    required: true
    default: ''
  version: # id of input
      description: 'test version'
      required: true
      default: ''
outputs:
  pods: # id of output
    description: 'All pods'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ask-config }}